### ISSUE TITLE
Adopt Secrets Protection Hook

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/community-registry-extensions#263]
### What type of extension are you looking for?

Hook

### Describe the extension you'd like to request

Per https://github.com/iann0036/cfn-hooks/tree/main/Generic-SecretsProtection-Hook

### Describe the solution you'd like

I'd like to republish the aforementioned hook into the community namespace. I don't believe any additional coding/configuration is needed, just a name change and adoption.

Happy to PR it myself.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ericzbeard** [comment]
Sounds good! Do you think you can handle the pipeline for the resource as well?
